CREATE TABLE IF NOT EXISTS Team(
    team_id INT GENERATED ALWAYS AS IDENTITY,
    leader INT NOT NULL,
    active BOOLEAN NOT NULL,
    team_name VARCHAR(255) NOT NULL 
);

ALTER TABLE 
    Team
ADD CONSTRAINT
    PK_TEAM PRIMARY KEY (team_id);

ALTER TABLE 
    Team
ADD CONSTRAINT
    FK_TEAM_LEADER FOREIGN KEY (leader) REFERENCES Users(user_id);
